version: '3.7'
services:
  image:
    build:
      context: ./src/services/image/
    networks: 
      - services
  profile:
    build:
      context: ./src/services/profile/
    networks: 
      - services
  pricing:
    depends_on: 
      - pricing_db
    build:
      context: ./src/services/pricing/
    networks: 
      - services
  pricing_db:
    image: microsoft/mssql-server-linux
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-server-linux-data:/var/opt/mssql/data
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Your_password123" -Q "SELECT 1" || exit 1
    networks: 
      - services

  web_api:
    build:
      context: ./src/web/api/
    ports: 
      - "5000:80"
    networks: 
      - backend
      - services

  site:
    build:
      context: ./src/web/site/
    ports:
      - "5001:80"

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.6.1
    depends_on:
      - elasticsearch
      - kibana
    cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
    cap_drop: ["ALL"]
    ports:
      - 8200:8200
    networks:
      - elastic
    command: >
        apm-server -e
          -E apm-server.rum.enabled=true
          -E setup.kibana.host=kibana:5601
          -E setup.template.settings.index.number_of_replicas=0
          -E apm-server.kibana.enabled=true
          -E apm-server.kibana.host=kibana:5601
          -E output.elasticsearch.hosts=["elasticsearch:9200"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=docker-cluster
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-XX:UseAVX=2 -Xms1g -Xmx1g
    ulimits:
      memlock:
        hard: -1
        soft: -1
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS= http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elastic
    
volumes:
  mssql-server-linux-data: 

networks: 
  backend:
  services:
  elastic:
    driver: bridge