version: '3.7'
services:
  image:
    build:
      context: ./src/services/image/
    networks: 
      - services
  profile:
    build:
      context: ./src/services/profile/
    networks: 
      - services
  pricing:
    depends_on: 
      - pricing_db
    build:
      context: ./src/services/pricing/
    networks: 
      - services
  pricing_db:
    image: microsoft/mssql-server-linux
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-server-linux-data:/var/opt/mssql/data
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Your_password123" -Q "SELECT 1" || exit 1
    networks: 
      - services

  web_api:
    build:
      context: ./src/web/api/
    ports: 
      - "5000:80"
    networks: 
      - backend
      - services


volumes:
  mssql-server-linux-data: 

networks: 
  frontend:
  backend:
  services: