version: '3.7'
services:
  image:
    container_name: image-service
    build:
      context: ./src/services/image/
    networks: 
      - services
  profile:
    container_name: profile-service
    build:
      context: ./src/services/profile/
    networks: 
      - services
  pricing:
    container_name: pricing-service
    build:
      context: ./src/services/pricing/
    networks: 
      - services
networks: 
  frontend:
  backend:
  services: