version: "3.7"
services:

  bid:
    build:
      context: ./src/services/bid/
    depends_on:
      bid_db:
        condition: service_healthy
    environment:
      - ELASTIC_APM_ENABLED=false
      - BID_CONNECTION_STRING=Server=bid_db;Database=master;User=sa;Password=Your_password123;
    networks:
      - services
      - bid

  bid_db:
    image: mcr.microsoft.com/mssql/server
    hostname: bid_db
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    healthcheck:
      interval: 10s
      retries: 12
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Your_password123" -Q "SELECT 1" || exit 1
    networks:
      - bid

  image:
    build:
      context: ./src/services/image/
    environment:
      - ELASTIC_APM_ENABLED=false
    networks:
      - services

  profile:
    build:
      context: ./src/services/profile
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      - ELASTIC_APM_ENABLED=false
    networks:
      - services
    ports:
      - "5002:8080"

  pricing:
    hostname: pricing
    depends_on:
      pricing_db:
        condition: service_healthy
    restart: always
    build:
      context: ./src/services/pricing/
    environment:
      - ELASTIC_APM_ENABLED=false
    networks:
      - services
      - pricing

  pricing_db:
    image: mcr.microsoft.com/mssql/server
    hostname: pricing_db
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    healthcheck:
      interval: 10s
      retries: 12
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Your_password123" -Q "SELECT 1" || exit 1
    networks:
      - pricing

  web_api:
    build:
      context: ./src/web/api/
    ports:
      - "5000:80"
    environment:
      - ELASTIC_APM_ENABLED=false    
    networks:
      - backend
      - services

  site:
    build:
      context: ./src/web/site/
    ports:
      - "5001:80"

networks:
  backend:
  services:
  pricing:
  bid: